[phases.setup]
aptPkgs = [
  "chromium",
  "chromium-sandbox",
  "libgbm-dev",
  "libnss3",
  "libatk1.0-0",
  "libatk-bridge2.0-0",
  "libcups2",
  "libdrm2",
  "libxkbcommon0",
  "libxcomposite1",
  "libxdamage1",
  "libxfixes3",
  "libxrandr2",
  "libpango-1.0-0",
  "libcairo2",
  "libasound2"
]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npx prisma generate", "npx prisma migrate deploy", "npm run build"]

[start]
cmd = "npm start"